<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'CONTACT フォーム の送信',
	'heading' => '新規フォームの送信',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'チェック済み',
		'checkbox_unchecked' => '未チェック',
		'submitted_from' => 'Web サイトから送信されたフォーム : %s',
		'submitted_by' => '訪問者の IP アドレス : %s',
		'too_many_submissions' => '最近、この IP からの送信回数が多すぎます',
		'failed_to_send_email' => '電子メールの送信に失敗しました',
		'invalid_reCAPTCHA_private_key' => '無効な reCAPTCHA プライベートキーです。',
		'invalid_reCAPTCHA2_private_key' => '無効な reCAPTCHA 2.0 プライベートキーです。',
		'invalid_reCAPTCHA2_server_response' => '無効な reCAPTCHA 2.0 サーバー応答です。',
		'invalid_field_type' => '不明なフィールドの種類「%s」です。',
		'invalid_form_config' => 'フィールド「%s」には無効な設定が含まれています。',
		'unknown_method' => '不明なサーバー要求メソッド'
	),
	'email' => array(
		'from' => 'info@mikasa-eng.co.jp',
		'to' => 'info@mikasa-eng.co.jp'
	),
	'fields' => array(
		'custom_U1649' => array(
			'order' => 2,
			'type' => 'string',
			'label' => '名前',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「名前」が必要です。'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => '電子メールアドレス',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「電子メールアドレス」が必要です。',
				'format' => 'フィールド「電子メールアドレス」には無効な電子メールが含まれています。'
			)
		),
		'custom_U1677' => array(
			'order' => 4,
			'type' => 'string',
			'label' => '会社名',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「会社名」が必要です。'
			)
		),
		'custom_U1654' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'メッセージ',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「メッセージ」が必要です。'
			)
		),
		'custom_U2240' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '件名',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「件名」が必要です。'
			)
		)
	)
);

process_form($form);
?>
